project_id = "konbogydmhjhrlaskbgv"

[functions.publish-scheduled-videos]
verify_jwt = false

[functions.get-optimal-schedule-times]
verify_jwt = false

[functions.trigger-flash-sale]
verify_jwt = false